FROM node:20.8-buster-slim AS dev

ENV WORKPATH /opt/workdir/
ENV USERNAME=node
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN usermod -u ${USER_ID} ${USERNAME}
RUN usermod -g ${GROUP_ID} ${USERNAME}

# RUN mkdir -p ${WORKPATH}/node_modules && chown -R ${USERNAME}:${USERNAME} ${WORKPATH}
RUN mkdir -p /usr/local/lib/node_modules/
WORKDIR ${WORKPATH}

RUN npm install -g create-vite@4.4.0
USER ${USERNAME}

CMD ["/bin/true"]
